### PR TITLE
Feat/limit kube apiserv mem

### LINKED ISSUE #516: memory limits for kube-apiserver
As an operator of k8s clusters, I want to avoid the kube-apiservers to eat all memory ending up killing etcd (or the entire node).

Adapted from random k8s tip from @horazont in today's community call.

Let's quickly check whether this is something that affects us and could be addressed easily.

### PR DESCRIPTION
**Pull request by garloff**
This limits both CPU and Mem usage to 75% of what the control plane node offers.
With our default sizing (SCS-2V-4), this means max 1.5 vCPUs and 2.875GiB of memory for kube-apiserver.
Goal is to avoid an overwhelmed kube-apiserver causing the control plane node (and especially etcd) to become completely dysfunctional.
Fixes #516.

### CODE REVIEW

**Comment by garloff** [comment]
Not yet perfect: `k --context testcl7-admin@testcl7 -n kube-system get pod kube-apiserver-capi5-testcl7-control-plane-genc01-gwsj2 -o yaml`
```yaml
    resources:                                                                    
      limits:                                                                     
        cpu: 1500m                
        memory: 2944M    
      requests:        
        cpu: 250m                                                                 
        memory: 2944M              
```
The limit seems to implicitly also serve as request, so we end up filling up the control node and potentially preventing other services from running.

**Comment by garloff** [comment]
```yaml
    resources:
      limits:
        cpu: 1500m
        memory: 2944M
      requests:
        cpu: 250m
        memory: 512M
```
This looks better now ...

**Comment by garloff** [comment]
If this is common enough to emerge as a problem, should we mention this improvement in the release notes?

**Comment by garloff** [comment]
> I was also working on this but have not made it work so far. I pushed the changes here:
> 
> [fdobrovolny@4043cdf](https://github.com/fdobrovolny/scs-k8s-cluster-api-provider/commit/4043cdf5f3bbb19c61ba4d58966e88d519e6305b)

I see you wanted to make this configurable ...
I was taking an easier route, just providing sane defaults without any tuning options.
Rationale:
* Too many choices can be overwhelming (even if they always have good defaults, bad if they don't).
* I consider this a quality/robustness of implementation thing, not so much a tunable that should be touched.
* We will migrate to SCS KaaS v2 with cluster stack in a few months. And carrying forward all these options is some extra work. If some of it comes later (to ensure the quality of implementation surpasses the old solution in most areas), it's easier if it's hidden ...

**Comment by garloff** [comment]
> From my testing, I was able to make apiserver to die from OOM using the `kue-burner`. However in the end it was consuming all the CPU so I like that we limit the CPU usage as well. I managed to kill it using 100 requests per second it took a few minutes to die.

It will die also with the mem and cpu limits I guess -- although the CPU limit may have a bit of a throttling effect that allows it to survive a bit longer. What the limits should do is that the rest of the system -- especially etcd, but possibly also CNI controller -- still have enough resources to work reasonably well until kube-apiserver gets OOM killed.

If you have time to test with `kube-burner` again, it would be interesting to see how the control plane nodes fares with the current setting and check if reserved mem and cpu capacity are reasonably well tuned.

**Comment by fdobrovolny** [comment]
> If this is common enough to emerge as a problem, should we mention this improvement in the release notes?

I think it deserves to be mentioned in the new features part. Some users may already have this implemented manually.

> I see you wanted to make this configurable ...
I was taking an easier route, just providing sane defaults without any tuning options.
Rationale

I guess I do see the beauty in that 99% of users will never need to change it or even know that it's there and it just works. But I also ultimately like the fact that if I need to, I can change the cluster template and edit it without too much hassle.

> If you have time to test with kube-burner again, it would be interesting to see how the control plane nodes fares with the current setting and check if reserved mem and cpu capacity are reasonably well tuned.

I'll try to test it and report back.

**Comment by garloff** [comment]
Feel free to improve the text. Or just merge if it's fine.

**Review by matofeder — APPROVED** [review]
/tested

Test result:
- Kubeapiserver running on the control plane node with flavor `SCS-2V:4:20` got the following resource limits:

```bash
$ k get pod -n kube-system kube-apiserver-gx-scs-k8s-gx-scs-k8s-control-plane-genc01-zvbn5  -o=jsonpath='{.spec.containers[0].resources.limits}' | jq
{
  "cpu": "1500m",
  "memory": "2944M"
}

```

The above matches the 75% of resources available on the underlying control plane node. 

/lgtm

**Pull request merged**
