### PR TITLE
Make cilium the default CNI.

### PR DESCRIPTION
**Pull request by garloff**
Probably merge this after #430.

### CODE REVIEW

**Review by chess-knight — APPROVED** [review]
LGTM!

**Comment by garloff** [comment]
Revisit #144 before we merge this.

**Comment by garloff** [comment]
Adding work-in-progress label to remind ourselves, that we want to determine the future of the remaining Node Port check failure tracked in #144 before merging this one.

**Comment by jschoone** [comment]
Please make sure sonobuoy tests pass.

**Comment by chess-knight** [comment]
Hello @jschoone, see my https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/144#issuecomment-1655774046  where I little dived into it.

**Comment by chess-knight** [comment]
We are able to pass conformance tests with #489

**Comment by mxmxchere** [comment]
Blocker #144 is removed.

**Pull request merged**
