### PR TITLE
Adjust to new kustomize syntax.

### PR DESCRIPTION
**Pull request by garloff**
Use resources rather than base.
Insert path: before filenames referenced in patches. Reference: https://github.com/kubernetes-sigs/kustomize/pull/4911 Supercedes: https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/329

### CODE REVIEW

**Comment by garloff** [comment]
Your reviews would be welcome!

**Review by jschoone — APPROVED** [review]
Just tested and works for me.
I closed #329 without merging.

**Comment by Nils98Ar** [comment]
@garloff Can this also be merged into maintained/v4.x? Otherwise we would need to switch to main.

**Comment by garloff** [comment]
Thanks, @Nils98Ar, this bugfix should definitely go to v4.x and also v4.0.x.
I have already merged (cherry-picked) this kustomize fix into both branches.

Honestly, I was a bit unsure how much those maintained branches are in use and we have not given them as much attention lately.
I opened issue #369 and #370 to discuss and track what we backport in terms of bugfixes and (in case of v4.x) minor updates.

**Pull request merged**
