### PR TITLE
Add server metadata, soft-anti-affinity and local ssd flavors for gx-scs

### LINKED ISSUE #741: Fix daily e2e pipeline
https://zuul.scs.community/t/SCS/builds?job_name=k8s-cluster-api-provider-e2e-conformance&project=SovereignCloudStack/k8s-cluster-api-provider

### PR DESCRIPTION
**Pull request by chess-knight**
Fixes #741

### CODE REVIEW

**Comment by chess-knight** [comment]
> Build failed (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/cc45695c8a78434084a51aed9bd41a00
> 
> ❌ [k8s-cluster-api-provider-e2e-quick ](https://zuul.scs.community/t/SCS/build/2d12acd37d1e4af4bd0b651a89173eef) **TIMED_OUT** in 1h 04m 00s
> 
> Warning:
> 
> Sonobouy results

*Fault*
**Message** No valid host was found. There are not enough hosts available.
**Code** 500
**Details**
**Created** June 17, 2024, 5:20 a.m.

It seems like there are not enough hosts for 3 *"SCS-2V-4-20s"* control-plane nodes with an anti-affinity policy.

**Comment by chess-knight** [comment]
> Build succeeded (e2e-quick-test pipeline). https://zuul.scs.community/t/SCS/buildset/cf6946aacb7442c39cbd754c0b0e6311
> 
> ✔️ [k8s-cluster-api-provider-e2e-quick ](https://zuul.scs.community/t/SCS/build/dc654299a732463cb49f45c112567f6d) SUCCESS in 39m 15s
> 
> Warning:
> 
> SCS Compliance results
> Sonobouy results
> ## Custom ENV config
> ```
> anti_affinity = false
> ```

After https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/742#issuecomment-2172345136 I tried `anti_affinity = false` with success.

**Comment by chess-knight** [comment]
@frosty-geek, I tested the *"SCS-2V-4-20s"* flavor, but it seems like there are currently only two hosts available for that, is it true?

**Comment by frosty-geek** [comment]
> It seems like there are only two hosts available for _"SCS-2V-4-20s"_ flavor right now, but we have 3 control-plane nodes with an anti-affinity policy here.

I checked and yes atm that is correct, we're in the process of fixing that with a new hardware environment (scs2) which will hopefully hit ~mid july

**Comment by chess-knight** [comment]
Soft-anti-affinity was used in https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/742#issuecomment-2182913903 but control planes were scheduled on the same host. It was not the case in https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/742#issuecomment-2186489548.

**Review by matofeder — APPROVED** [review]
Tested by the e2e pipeline and works as expected.
The change looks good to me

**Review by michal-gubricky — APPROVED** [review]
lgtm

**Pull request merged**
