### PR TITLE
Remove deprecated ETCD_PRIO_BOOST.

### LINKED ISSUE #359: Remove deprecated etcd_prio_boost
We had deprecated etcd_prio_boost in R3 and should remove it in R4.
Do this. One less pararmeter to confuse anyone.

### PR DESCRIPTION
**Pull request by garloff**
It's always enabled since R3, was deprecated and ignored there. Fixes #359.

### CODE REVIEW

**Comment by garloff** [comment]
@aov-arnold: Can we invite you here as well?

**Review by matofeder — COMMENTED** [review]
Consider to adjust/remove README.md lines 383,384 where ETCD_PRIO_BOOST is also mentioned:
```
We now always use slower heartbeat (250ms) and increase CPU and IO priority
which used to be controlled by `ETCD_PRIO_BOOST`. This is safe.
```

Overall LGTM!

**Comment by Nils98Ar** [comment]
> @aov-arnold: Can we invite you here as well?

Yes you can! But I will no longer use this „aov account“ and switch to my personal one @Nils98Ar instead.

**Comment by aov-arnold** [comment]
> @aov-arnold: Can we invite you here as well?

Yes you can! But I will no longer use this „aov account“ and switch to my personal one @Nils98Ar instead.

**Comment by garloff** [comment]
> Consider to adjust/remove README.md lines 383,384 where ETCD_PRIO_BOOST is also mentioned:
> ```
> We now always use slower heartbeat (250ms) and increase CPU and IO priority
> which used to be controlled by `ETCD_PRIO_BOOST`. This is safe.
> ```
> 
> Overall LGTM!

Well, it's stating a bit of history...
Maybe remove the reference for R5?

**Comment by garloff** [comment]
Sidenote: To merge this, I'd need an approving review.

**Comment by matofeder** [comment]
> Well, it's stating a bit of history... Maybe remove the reference for R5?

works for me

**Review by matofeder — APPROVED** [review]

**Pull request merged**
