### PR TITLE
Backport sprint Jena to `maintained/v5.x` #532

### PR DESCRIPTION
**Pull request by chess-knight**
Related to #532

### CODE REVIEW

**Comment by chess-knight** [comment]
Calico:
```
=== Collecting results ===
INFO[0000] delete request issued                         dry-run=false kind=namespace namespace=sonobuoy
INFO[0000] delete request issued                         dry-run=false kind=clusterrolebindings names="[sonobuoy-serviceaccount-sonobuoy]"
INFO[0000] delete request issued                         dry-run=false kind=clusterroles names="[sonobuoy-serviceaccount-sonobuoy]"
Plugin: e2e
Status: passed
Total: 7211
Passed: 382
Failed: 0
Skipped: 6829

Plugin: systemd-logs
Status: passed
Total: 6
Passed: 6
Failed: 0
Skipped: 0

Run Details:
API Server version: v1.27.5
Node health: 6/6 (100%)
Pods health: 51/51 (100%)
```

**Comment by chess-knight** [comment]
Cilium:
```
=== Collecting results ===
INFO[0000] delete request issued                         dry-run=false kind=namespace namespace=sonobuoy
INFO[0000] delete request issued                         dry-run=false kind=clusterrolebindings names="[sonobuoy-serviceaccount-sonobuoy]"
INFO[0000] delete request issued                         dry-run=false kind=clusterroles names="[sonobuoy-serviceaccount-sonobuoy]"
Plugin: e2e
Status: failed
Total: 7211
Passed: 381
Failed: 1
Skipped: 6829

Failed tests:
[It] [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should validate Statefulset Status endpoints [Conformance]

Plugin: systemd-logs
Status: passed
Total: 6
Passed: 6
Failed: 0
Skipped: 0

Run Details:
API Server version: v1.27.5
Node health: 6/6 (100%)
Pods health: 48/50 (96%)
```

**Comment by chess-knight** [comment]
Cilium - next run of e2e conformance tests:
```
=== Collecting results ===
INFO[0000] delete request issued                         dry-run=false kind=namespace namespace=sonobuoy
INFO[0000] delete request issued                         dry-run=false kind=clusterrolebindings names="[sonobuoy-serviceaccount-sonobuoy]"
INFO[0000] delete request issued                         dry-run=false kind=clusterroles names="[sonobuoy-serviceaccount-sonobuoy]"
Plugin: e2e
Status: passed
Total: 7211
Passed: 382
Failed: 0
Skipped: 6829

Plugin: systemd-logs
Status: passed
Total: 6
Passed: 6
Failed: 0
Skipped: 0

Run Details:
API Server version: v1.27.5
Node health: 6/6 (100%)
Pods health: 51/51 (100%)
```

**Review by michal-gubricky — APPROVED** [review]
lgtm

**Review by DEiselt — APPROVED** [review]

**Pull request merged**
