### PR TITLE
Fix kustomization of nginx ingress

### LINKED ISSUE #328: Kustomize errors when building nginx manifests
I always face the error
```
Error: invalid Kustomization: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
```
This comes from the `kustomize build` lines from `apply_nginx_ingress.sh`
Using `kubectl kustomize` seems to fix this issue, I will create a PR.

### PR DESCRIPTION
**Pull request by jschoone**
Fixes #328

### CODE REVIEW

**Review by chess-knight — APPROVED** [review]
I tested it and it seems it works.

**Review by batistein — APPROVED** [review]

**Comment by garloff** [comment]
As per discussion in the Container Team meeting:
* kustomize has changed upstream and we probably need to adjust our kustomization for it to pass
* kubectl kustomize still has an older version of kustomize included which is the reason for it to still work
* As soon as the kubectl included kustomize gets revved, we'd break again

Suggested way forward:
(a) Adjust the kustomization files such that they are processed successfuly through kustomize v5
Only if this fails:
(b) Find a way to reliably get and pin an older version of kustomize (via kubectl or directly)

**Comment by garloff** [comment]
Reading through https://github.com/kubernetes-sigs/kustomize/pull/4911, I guess that we just need to replace patches: with patchesStrategicMerge: in the kustomization files to be compatible with kustomize v5 (and v3).

**Comment by garloff** [comment]
Better to fully update the syntax and use `resources` instead of `base` and `patches:\n  - path: FILENAME` instead of `patchesStrategicMerge:\n  - FILENAME`.

**Pull request closed without merging**
