### PR TITLE
Fix command not found in Makefile

### PR DESCRIPTION
**Pull request by chess-knight**
Fix also sonobuoy.sh usage

### CODE REVIEW

**Review by garloff — COMMENTED** [review]
Hmm, shouldn't we then call '~/bin/script' rather than 'bin/script' ? I meant to have '~/bin' in 'PATH' . Apparently that's not universally the case. You rely on '.' being part of 'PATH', I'm not sure this is always true.

**Comment by chess-knight** [comment]
> Hmm, shouldn't we then call `~/bin/script` rather than `bin/script` ? I meant to have `~/bin` in `PATH` . Apparently that's not universally the case. You rely on `. `being part of `PATH`, I'm not sure this is always true.

I found this PR #150 where the same approach is used. Maybe we can add `~/` to all occurrences in the Makefile to make it more robust. What do you think @garloff?

**Comment by garloff** [comment]
> aybe we can add `~/` to all occurrences in the Makefile to make it more robust. What do you think @garloff?

Yes, let's do this.

**Comment by chess-knight** [comment]
> Yes, let's do this.

See 3c80118fff77cf2dd2ce9e552f01301d19c34925

**Review by garloff — APPROVED** [review]
Thanks, looks good to me.

**Pull request merged**
