### PR TITLE
Deploy snapshot controller to enable enable the volume snapshot feature

### PR DESCRIPTION
**Pull request by chess-knight**
See #408

Snapshots now can be created, e.g. following this [tutorial](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/features.md#volume-snapshots).

### CODE REVIEW

**Comment by garloff** [comment]
Patch looks good, thanks.
Want to add a line to the docs and to the release notes for R5?

**Comment by chess-knight** [comment]
> Want to add a line to the docs and to the release notes for R5?

Yeah of course, where should I put the information?

**Review by garloff — APPROVED** [review]
@chess-knight @matofeder
Please check the release notes snippet for correctness.
Once this is good, we are ready to go.

**Comment by chess-knight** [comment]
> Please check the release notes snippet for correctness.

LGTM!

**Pull request merged**
