### PR TITLE
Add support to restrict access to the management server

### PR DESCRIPTION
**Pull request by NotTheEvilOne**
This PR provides support to restrict access to the management server based on a list of CIDRs.

### CODE REVIEW

**Comment by jschoone** [comment]
Hi @NotTheEvilOne, looks like the [test results](https://zuul.scs.community/t/SCS/build/b4739ee52b9c4a2ba3413c1251f8e8d6) approve the restriction works? 😄

**Comment by NotTheEvilOne** [comment]
The issue with the failing e2e test is weird.

```
2023-09-27 16:26:39.529585 | ubuntu-jammy | terraform_data.mgmtcluster_containerd_registry_host_files["./files/containerd/docker.io"] (remote-exec): Connecting to remote host via SSH...
...
2023-09-27 16:26:39.707973 | ubuntu-jammy | terraform_data.mgmtcluster_containerd_registry_host_files["./files/containerd/docker.io"] (remote-exec): Connected!
```
clearly indicates that the SSH connection (which is what this PR changes). As manual testing shows no side effects it seems to be related to our test environment? @matofeder could you have a look with your colleagues if something on the Zuul side gives more details what's going wrong here?

**Comment by matofeder** [comment]
> The issue with the failing e2e test is weird.
> 
> ```
> 2023-09-27 16:26:39.529585 | ubuntu-jammy | terraform_data.mgmtcluster_containerd_registry_host_files["./files/containerd/docker.io"] (remote-exec): Connecting to remote host via SSH...
> ...
> 2023-09-27 16:26:39.707973 | ubuntu-jammy | terraform_data.mgmtcluster_containerd_registry_host_files["./files/containerd/docker.io"] (remote-exec): Connected!
> ```
> 
> clearly indicates that the SSH connection (which is what this PR changes) works in it's default setting as before. As manual testing shows no side effects it seems to be related to our test environment? @matofeder could you have a look with your colleagues if something on the Zuul side gives more details what's going wrong here?

Hi,

You are right, the failed e2e test was Zuul related. 

The reason is that Zuul executes the e2e test on your feature branch that is already merged with the most recent main, i.e. Zuul merges your feature branch with the most recent main before e2e execution on it. 
But when you executed the e2e test, your feature branch was not up-to-date with the most recent main. 

This may lead to some unexpected issues, as we can see right now, and should be improved (i will create an issue for this)

This diff in your non-updated and updated feature branch causes the e2e test was executed with a patch  [#587](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/587) (capo v0.8.0) but the feature branch clone in  
 the management node did not contain this patch. As a result, deployed v0.8.0 capo resources (see related [log](https://zuul.scs.community/t/SCS/build/141a6601d8c74e608ae0560382a597ab/log/job-output.txt#3280)) wanted to be patched with capo v0.7.3 patch that was cloned in the non-updated feature branch (see related [log](https://zuul.scs.community/t/SCS/build/141a6601d8c74e608ae0560382a597ab/log/job-output.txt#3799)). This caused the error. 

So after the feature branch update the e2e test passed.

I appreciate you bringing this to my attention, as I wrote the follow-up issue will come soon.

**Review by matofeder — APPROVED** [review]
/lgtm

**Review by chess-knight — APPROVED** [review]

**Review by DEiselt — APPROVED** [review]

**Pull request merged**
