### PR TITLE
WIP: Test Zuul minimal

### PR DESCRIPTION
**Pull request by matofeder**
A minimal Zuul CI configuration PR, created only for SCS Zuul testing purposes 

- This configuration assigned `test-zuul-job` job to the SCS [check](https://github.com/SovereignCloudStack/zuul-config/blob/main/zuul.d/gh_pipelines.yaml#L3) pipeline. 

- SCS check pipeline should trigger the job execution when PR is `opened`, `changed`, or `reopened` or if a comment with `recheck` content is added to the PR

This minimal Zuul CI configuration PR has been successfully tested in the dNation development Zuul instance, see related PR https://github.com/matofederorg/k8s-cluster-api-provider/pull/18

### CODE REVIEW

**Comment by matofeder** [comment]
recheck

**Comment by o-otte** [comment]
recheck

**Comment by o-otte** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
SCS Zuul works - this is not needed anymore

**Pull request closed without merging**
