### PR TITLE
Replace Terraform with OpenTofu

### LINKED ISSUE #594: Replace Terraform with OpenTofu

### PR DESCRIPTION
**Pull request by chess-knight**
Resolves #594

### CODE REVIEW

**Comment by berendt** [comment]
Let's wait for the final 1.6.0 release. I think this should be soon available.

**Comment by berendt** [comment]
In the Zuul there is also a ensure-terraform job. We should also add an ensure-opentofu job.

**Comment by jschoone** [comment]
Hi @chess-knight, looks like OpenTofu 1.6.0 is now stable

**Comment by chess-knight** [comment]
> Hi @chess-knight, looks like OpenTofu 1.6.0 is now stable

Thank you @jschoone for the notification, I updated and tested the v1.6.0 version successfully. Also, I replaced terraform with opentofu in the docs and marked this PR as ready for review.

**Review by berendt — COMMENTED** [review]
LGTM. Read only. No test.

**Review by jschoone — APPROVED** [review]

**Pull request merged**
