### PR TITLE
Update maintained/v5.x (#443)

### PR DESCRIPTION
**Pull request by fdobrovolny**
Issue #443

### CODE REVIEW

**Comment by fdobrovolny** [comment]
There seems to be something broken with makefile when I'm on main the `make mycloud` functions normally. Here following happens:

```
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.clouds."testfd1"': [Errno 2] No such file or directory: '.clouds."testfd1"'
make: *** [Makefile:68: mycloud] Chyba 2
```

Investigating where the issue is.

**Comment by fdobrovolny** [comment]
The culprit seems to be #392

**Comment by fdobrovolny** [comment]
Sonobuoy result with Cilium turned on:

```
Sonobuoy plugins have completed. Preparing results for download.
2023-07-13T11:19:39Z
         PLUGIN     STATUS   RESULT   COUNT                 PROGRESS
            e2e   complete   failed       1   Passed:357, Failed:  1
   systemd-logs   complete   passed       3                         

Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
=== Collecting results ===
time="2023-07-13T11:19:46Z" level=info msg="delete request issued" dry-run=false kind=namespace namespace=sonobuoy
time="2023-07-13T11:19:46Z" level=info msg="delete request issued" dry-run=false kind=clusterrolebindings names="[sonobuoy-serviceaccount-sonobuoy]"
time="2023-07-13T11:19:46Z" level=info msg="delete request issued" dry-run=false kind=clusterroles names="[sonobuoy-serviceaccount-sonobuoy]"
Plugin: e2e
Status: failed
Total: 7069
Passed: 360
Failed: 1
Skipped: 6708

Failed tests:
[It] [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]

Plugin: systemd-logs
Status: passed
Total: 3
Passed: 3
Failed: 0
Skipped: 0

Run Details:
API Server version: v1.25.11
Node health: 3/3 (100%)
Pods health: 28/29 (96%)
Details for failed pods:
sonobuoy/sonobuoy-e2e-job-58fd96bfbbf14d23 Ready:False: PodFailed: 
Errors detected in files:
Warnings:
1848 podlogs/kube-system/etcd-fd-testfd1-control-plane-genc01-rb5k6/logs/etcd.txt
1180 podlogs/kube-system/kube-controller-manager-fd-testfd1-control-plane-genc01-rb5k6/logs/kube-controller-manager.txt
 455 podlogs/kube-system/cilium-89pkc/logs/cilium-agent.txt
 369 podlogs/kube-system/cilium-smxbf/logs/cilium-agent.txt
 102 podlogs/kube-system/kube-apiserver-fd-testfd1-control-plane-genc01-rb5k6/logs/kube-apiserver.txt
  46 podlogs/kube-system/kube-scheduler-fd-testfd1-control-plane-genc01-rb5k6/logs/kube-scheduler.txt
  33 podlogs/sonobuoy/sonobuoy-e2e-job-58fd96bfbbf14d23/logs/e2e.txt
  16 podlogs/kube-system/openstack-cloud-controller-manager-d2smg/logs/openstack-cloud-controller-manager.txt
  15 podlogs/kube-system/cilium-nbdjc/logs/cilium-agent.txt
   8 podlogs/kube-system/csi-cinder-controllerplugin-76768c4596-mqr72/logs/csi-attacher.txt
   8 podlogs/kube-system/csi-cinder-controllerplugin-76768c4596-mqr72/logs/csi-provisioner.txt
   3 podlogs/kube-system/csi-cinder-nodeplugin-cxnq5/logs/node-driver-registrar.txt
   3 podlogs/kube-system/csi-cinder-controllerplugin-76768c4596-mqr72/logs/csi-snapshotter.txt
   3 podlogs/kube-system/kube-proxy-9fbmt/logs/kube-proxy.txt
   2 podlogs/kube-system/csi-cinder-nodeplugin-xk2dd/logs/node-driver-registrar.txt
   2 podlogs/kube-system/csi-cinder-nodeplugin-2zrqm/logs/node-driver-registrar.txt
   1 podlogs/kube-system/csi-cinder-nodeplugin-2zrqm/logs/liveness-probe.txt
   1 podlogs/sonobuoy/sonobuoy/logs/kube-sonobuoy.txt
   1 podlogs/kube-system/csi-cinder-nodeplugin-xk2dd/logs/liveness-probe.txt
   1 podlogs/kube-system/metrics-server-78f5fc6577-cvdw7/logs/metrics-server.txt
   1 podlogs/kube-system/csi-cinder-nodeplugin-cxnq5/logs/liveness-probe.txt
Errors:
2502 podlogs/kube-system/kube-controller-manager-fd-testfd1-control-plane-genc01-rb5k6/logs/kube-controller-manager.txt
 908 podlogs/sonobuoy/sonobuoy-e2e-job-58fd96bfbbf14d23/logs/e2e.txt
 740 podlogs/kube-system/snapshot-controller-554544fbbd-49bfx/logs/snapshot-controller.txt
 469 podlogs/kube-system/cilium-89pkc/logs/cilium-agent.txt
 364 podlogs/kube-system/cilium-smxbf/logs/cilium-agent.txt
 297 podlogs/kube-system/kube-proxy-9fbmt/logs/kube-proxy.txt
 107 podlogs/kube-system/kube-apiserver-fd-testfd1-control-plane-genc01-rb5k6/logs/kube-apiserver.txt
 100 podlogs/kube-system/kube-scheduler-fd-testfd1-control-plane-genc01-rb5k6/logs/kube-scheduler.txt
  17 podlogs/kube-system/openstack-cloud-controller-manager-d2smg/logs/openstack-cloud-controller-manager.txt
   8 podlogs/kube-system/kube-proxy-bhthk/logs/kube-proxy.txt
   8 podlogs/kube-system/kube-proxy-wgn4z/logs/kube-proxy.txt
   7 podlogs/kube-system/cilium-nbdjc/logs/cilium-agent.txt
   5 podlogs/kube-system/etcd-fd-testfd1-control-plane-genc01-rb5k6/logs/etcd.txt
   1 podlogs/kube-system/csi-cinder-nodeplugin-xk2dd/logs/node-driver-registrar.txt
   1 podlogs/kube-system/csi-cinder-nodeplugin-cxnq5/logs/node-driver-registrar.txt
   1 podlogs/kube-system/csi-cinder-nodeplugin-2zrqm/logs/node-driver-registrar.txt
time="2023-07-13T11:19:59Z" level=info msg="already deleted" dry-run=false kind=namespace namespace=sonobuoy
time="2023-07-13T11:19:59Z" level=info msg="delete request issued" dry-run=false kind=clusterrolebindings names="[]"
time="2023-07-13T11:19:59Z" level=info msg="delete request issued" dry-run=false kind=clusterroles names="[]"

Namespace "sonobuoy" has been deleted

Deleted all ClusterRoles and ClusterRoleBindings.

All E2E namespaces deleted
FAIL: Investigate 202307130940_sonobuoy_bc9e0871-8dc8-4316-9f28-61b218024d10.tar.gz for further inspection
```

**Comment by chess-knight** [comment]
> Sonobuoy result with Cilium turned on:

@fdobrovolny, see #144 for the Cilium HostPort problem

**Comment by fdobrovolny** [comment]
Thanks to @chess-knight, the issue in cilium tests seems to be expected behaviour as #144 is not solved yet; therefore, this PR can move out of the draft. I've attached below the test results without Cilium enabled.

```
Sonobuoy has completed. Use `sonobuoy retrieve` to get results.                                                        
=== Collecting results ===                                 
INFO[0000] delete request issued                         dry-run=false kind=namespace namespace=sonobuoy                                                                                                                                      
INFO[0000] delete request issued                         dry-run=false kind=clusterrolebindings names="[sonobuoy-serviceaccount-sonobuoy]"
INFO[0000] delete request issued                         dry-run=false kind=clusterroles names="[sonobuoy-serviceaccount-sonobuoy]"
Plugin: e2e                                                
Status: passed                                             
Total: 7069                                                
Passed: 361                                                
Failed: 0                                                  
Skipped: 6708                                              

Plugin: systemd-logs                                       
Status: passed                                             
Total: 3                                                   
Passed: 3                                                  
Failed: 0                                                  
Skipped: 0                                                 

Run Details:                                               
API Server version: v1.25.11                               
Node health: 3/3 (100%)                                    
Pods health: 29/29 (100%)
```

**Review by chess-knight — COMMENTED** [review]
Please add also #472 and #424 as mentioned in #443

**Comment by fdobrovolny** [comment]
Updated with #472 and #424

**Comment by fdobrovolny** [comment]
```
Sonobuoy has completed. Use `sonobuoy retrieve` to get results.                                                                                                                                                                         
=== Collecting results ===                                                                                                                                                                                                              
INFO[0000] delete request issued                         dry-run=false kind=namespace namespace=sonobuoy                                                                                                                                
INFO[0000] delete request issued                         dry-run=false kind=clusterrolebindings names="[sonobuoy-serviceaccount-sonobuoy]"                                                                                              
INFO[0000] delete request issued                         dry-run=false kind=clusterroles names="[sonobuoy-serviceaccount-sonobuoy]"                                                                                                     
Plugin: e2e                                                                                                                                                                                                                             
Status: passed                                                                                                                                                                                                                          
Total: 7069                                                                                                                                                                                                                             
Passed: 363                                                                                                                                                                                                                             
Failed: 0                                                                                                                                                                                                                               
Skipped: 6706                                                                                                                                                                                                                           
                                                                                                                                                                                                                                        
Plugin: systemd-logs                                                                                                                                                                                                                    
Status: passed                                                                                                                                                                                                                          
Total: 3                                                                                                                                                                                                                                
Passed: 3                                                                                                                                                                                                                               
Failed: 0                                                                                                                                                                                                                               
Skipped: 0                                                                                                          
                                                                                                                                                                                                                                        
Run Details:                                                                                                                                                                                                                            
API Server version: v1.25.11                                                                                                                                                                                                            
Node health: 3/3 (100%)                                                                                                                                                                                                                 
Pods health: 29/29 (100%)
```

All seems good.

**Pull request merged**
